title: Emanuel Gonzalez | Cloud Solutions Architect
email: tu-email@example.com
description: Arquitectura Zero Trust, DevSecOps, SysOps y Automatización con IA.
baseurl: ""
url: "https://emanuelgm1998.github.io"
theme: minima
